<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>lowvatest</AssemblyName>
    <RootNamespace>lowvatest</RootNamespace>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <NoWarn>$(NoWarn);CS0169</NoWarn>
  </PropertyGroup>

</Project>
